### ISSUE TITLE
Does not work with node 9

### ISSUE THREAD

**Issue by bonustrack** [steemit/rpc-auth#12]
Install is failing on my localhost using Node v9. Here is the error:
```
error @steemit/rpc-auth@1.1.0: The engine "node" is incompatible with this module. Expected version "^8".
```

**Comment by jnordberg** [comment]
Just tried running the tests against node/9.4.0 and they fail with

```
not ok 2 rpc auth handles invalid requests
  AssertionError [ERR_ASSERTION]: 'ValidationError: Invalid encoded params (First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.)' == 'ValidationError: Invalid encoded params (The first argument must be one of type string, Buffer, ArrayBuffer, Array, or Array-li
      at Context.<anonymous> (test/index.ts:127:16)
      at step (test/index.ts:32:23)
      at Object.next (test/index.ts:13:53)
      at fulfilled (test/index.ts:4:58)
      at <anonymous>
      at runMicrotasksCallback (internal/process/next_tick.js:115:5)
      at process._tickCallback (internal/process/next_tick.js:150:11)
```

Don't have bandwidth to dig into this right now, node 8 which is LTS works fine :)
